### ISSUE TITLE
scritps/mk_container.sh: realpath says no such file or directory

### ISSUE THREAD

**Issue by NANASHI0X74** [insys-icom/M3_Container#23]
just tried copying a binary to rootfs_staging to build my own container. Unfortunately though, the script mk_container.sh failed to run at first: 
`$ scripts/mk_container.sh
realpath: scripts/..: No such file or directory
scripts/mk_container.sh: line 5: /scripts/common_settings.sh: No such file or directory`
I've noticed that this is caused by realpath, which appears to have issues with the double dots at the end of its argument: scripts/..
As a workaround, I just edited the script hardcoding the $TOPDIR variable

**Comment by m-kress** [comment]
What exaclty did you change? scripts/mk_container.sh doesn't need to be modified at all.

When you want to create your own container, please consider to use one of the existing ones and modify them to your needs. 

In order to pack a new container, modify the file with the list of the wished files, that should be copied into the Container. These list files are located in scripts/rootfs_list. This has the advantages
- that the file properties and permissions are set to what you want them to be
- the location of the file to be copied can be anywhere, e.g. in your closed_packages or working or elsewhere.

Example: copy scripts/create_container_default and rename it to something like create_container_my_own_one.sh
Then copy scripts/rootfs_lists/default.txt to scripts/rootfs_lists/my_own_one.txt

In your new create_container_my_own.one.sh you can replace the list file "default.txt" to "my_own_one.txt"
That way you can always reproduce building a container withouht the danger of forgetting to copy one file.

Eventually I didn't get your problem. In that case please tell me, from where you want to copy a file to which destination.

**Comment by NANASHI0X74** [comment]
ok, I can't reproduce it today after all.
my problem yesterday was in two lines of script that actually many of the scripts use: 
SCRIPTSDIR=$(dirname $0)
TOPDIR=$(realpath ${SCRIPTSDIR}/..)
realpath in the second line would output No such file or directory and I noticed that this happened for any path that ended with two slashes... I have no idea idea why that is though and restarting the container today seems to have fixed it.
btw, I've sort of semi-automatically generated the list of files in my own container's rootfs_list .txt file using stat and some vim macro magic, but do you have any advice on how to do that properly and automated? I don't suppose the existing lists in this repoository were typed by hand :)

**Comment by m-kress** [comment]
Hm, maybe you started the script accidentally not within the SDC container but on your local host? But this is as good as a guess as anything.

The lists are more or less static. It's intended that way, so not automatism could accidentally pull in files, which you do not want. Most of the time this file rarely changes, once you have most of it complete. 

A quite annoying thing is, when you have to pull in a huge ammount of single files, like for python or the nodeJS container. These can contain thousands of files. There you need some kind of script. An example is in rootfs_lists/nodejs.txt line 155 or in busybox.txt line 113. There we use gen_initramfs_list.sh and sed to automatically paste all files into a temporary text file. Copy/Paste this into your rootfs lists.txt and remove the files, that you really do not need.

With nodeJS it's difficult, but in Python container you could get rid of a lot of files, e.g. all the graphics and the sound classes. That way your resulting contianer gets even smaller, which reduced the time necessary for uploading or updating the whole container.

**Comment by m-kress** [comment]
Do you still have problems? If that is not the case, could we please close this issue?

**Comment by NANASHI0X74** [comment]
this issue can be closed because it isn't reproducible
